### ISSUE TITLE
Missing component msp/recaptcha

### ISSUE THREAD

**Issue by Amadeco** [magefan/module-blog-comments-recaptcha#3]
Good afternoon,

You did an update of the composer.json of your extension twelve days ago.

You removed requirement of msp/recaptcha in it.

I did an update of your extension (Magento 2.4.1) and it is not working anymore.
Indeed, you layout file call "MSP\ReCaptcha\Block\Frontend\ReCaptcha" but it is not implemented anymore.

I do not understand why you removed this one,

This is a mistake ?

Sincererly yours,

Ilan Parmentier

**Comment by magefan** [comment]
Hello @mageho,

Yes, this was a mistake. We have removed tag2.0.6 and created a new one 2.1.0 for Magento 2.4.x.

So if you use Magento 2.1.2-2.3.x - then use extension version 2.0.5
If you use Magento 2.4.x - then use extension version 2.1.0
